# Generated by Django 2.2.17 on 2021-02-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0004_auto_20210201_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-id']},
        ),
    ]
