# Generated by Django 2.2.17 on 2021-02-15 16:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0006_auto_20210214_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor.fields.RichTextField(db_index=True),
        ),
    ]
