# Generated by Django 2.2.17 on 2021-02-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0007_auto_20210215_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
