# Generated by Django 2.2.17 on 2021-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210210_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='hasker_pics/%Y/%m/%d/'),
        ),
    ]
